---
title: "pseudo_novelist_cv"
author: "Vincent Su"
date: "2025-04-04"
output: pdf_document
header-includes:
  - \usepackage{bm}
---



## Procedure:

**Preliminary**

- Fit the model on $(y_1, \ldots, y_T)$ for each of the $p$ time series.
- Compute in-sample 1-step-ahead forecast errors $\hat{e}_{t|t-1}$ for $t=2,3,\ldots,T$ 

(in case such as AR(2) should we exclude the first 2 obs?) 

\vspace{2em}

**Algorithm**  

**Input**: matrices $\bm{y}_t, \hat{\bm{e}}_{t|t-1} \in \mathbb{R}^{T-1 \times p}$  
**Output**: optimal NOVELIST matrix $\hat{W}_1^* \in \mathbb{R}^{p \times p}$, threshold scalar $\delta^*$  

for $i = n:T-1$ do  
\hspace*{1em} Training set $= \{ \hat{\bm{e}}_{t|t-1} : t = i-n+1, \dots, i \}$  
\hspace*{1em} for $\delta = 0:1$ by $x$ step do  
\hspace*{2em} Compute $\hat{R}_i$ using training set  
\hspace*{2em} Compute thresholded $\hat{R}_{i,\delta}$  
\hspace*{2em} Compute $\lambda_{i,\delta}$ using $\hat{R}_{i,\delta}$  
\hspace*{2em} $\hat{R}^{N}_{i,\delta} \leftarrow \lambda_{i,\delta} \hat{R}_{i,\delta} + (1 - \lambda_{i,\delta}) \hat{R}_i$  
\hspace*{2em} $\hat{W}^{N}_{i,\delta} \leftarrow \hat{D}^{1/2} \hat{R}^{N}_{i,\delta} \hat{D}^{1/2}$  
\hspace*{2em} Compute 1-step-ahead reconciled forecasts $\tilde {\bm{y}}_{i+1,\delta}$  
\hspace*{2em} $\tilde {\bm{e}}_{i+1,\delta} \leftarrow {\bm{y}}_{i+1} - \tilde {\bm{y}}_{i+1,\delta}$  
\hspace*{1em} end  
end  

<!-- TODO: different function of error,MSE RMSE -->
$\bar {\bm{e}}_\delta \leftarrow \text{mean}(\tilde {\bm{e}}_{i+1,\delta})$, for $i = n:T-1$  
$\delta^* \leftarrow \arg\min_{\delta \in \{0, x, 2x, \dots, 1\}} \bar {\bm{e}}_\delta$  
Compute $\lambda^*$ using $\delta^*$ on all training data  
Compute $\hat{W}_1^*$ using $\delta^*$ and $\lambda^*$ on all training data  

**Return** $\delta^*, \hat{W}_1^*$ 



<!-- 
We only fit the model once, on all available T by p data.
The fitted model will then compute in-sample 1-step-ahead base forecasts y^
Then compute in-sample 1-step-ahead base forecast error e^
-->


